name: fullstack-javascript-project-46

on: push

jobs:
  make-test:
    name: Runs tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: make install
        env:
          CI: true
      - name: Run tests
        run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.HEXLET_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true